### ISSUE TITLE
Guides documentation not available

### ISSUE THREAD

**Issue by jrcapablanca** [aws-samples/amazon-connect-step-by-step-guides-module-library#2]
The Guides documentation under https://d2ote8qdyv1arb.cloudfront.net/?path=/story/overview--page is not reachable.

**Comment by sajithkaimal** [comment]
Please use this updated storybook URL - https://d3irlmavjxd3d8.cloudfront.net/?path=/story/overview--page

**Comment by jrcapablanca** [comment]
Thank you
